sudo: required
dist: trusty
language: node_js
node_js:
- '6.9'
services:
  - docker
addons:
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta
before_install:
- export VERSION=`date +%Y%m%d%H%M`
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install -g @angular/cli
- npm install
- ng build
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
script:
- ng test --watch false
after_success:
- cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
- docker build -t jptttttt/front:$VERSION .
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push jptttttt/front:$VERSION
- docker tag jptttttt/front:$VERSION jptttttt/front:latest
# gloud part
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
# Add gcloud to $PATH
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud version
- openssl enc -aes-256-cbc -pass pass:$G_DEPLOYER_ENC_PASS -p -in secure/jpt-deployer-key.enc -out secure/jpt-deployer-key.json -base64 -d
- gcloud auth activate-service-account --key-file secure/jpt-deployer-key.json
- gcloud config set project "jpt-21"
- gcloud components install kubectl
- gcloud container clusters list
- gcloud compute instances list
- gcloud container get-server-config
- kubectl config get-contexts
- kubectl get pods


#deploy:
