sudo: required
dist: trusty
language: node_js
node_js:
- '6.9'
addons: 
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta
before_install:
- openssl aes-256-cbc -K $encrypted_8c4c93323157_key -iv $encrypted_8c4c93323157_iv
  -in gce.json.enc -out gce.json -d
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install -g @angular/cli
- npm install
- ng build
script:
- ng test --watch false
