sudo: required
dist: trusty
language: node_js
node_js:
- '6.9'
services:
  - docker
addons:
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta
before_install:
- export VERSION=`date +%Y%m%d%H%M`
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install -g @angular/cli
- npm install
- ng build
script:
- ng test --watch false
after_success:
- cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
- docker build -t jptttttt/front:$VERSION .
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push jptttttt/front:$VERSION;
#deploy:
