sudo: required
dist: trusty
language: node_js
node_js:
- '6.9'
services:
- docker
addons:
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta
before_install:
- openssl aes-256-cbc -K $encrypted_5c354d5aeeb4_key -iv $encrypted_5c354d5aeeb4_iv -in gce.json.enc -out gce.json -d
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install -g @angular/cli
- npm install
- ng build
script:
- ng test --watch false
after_success:
- cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: gae
  skip_cleanup: true
  project: jpt-2-162623
  keyfile: gce.json
  verbosity: debug
  on: develop
